include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    depend_on_referenced_packages: false
    prefer_is_not_empty: true
    prefer_is_empty: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
